### ISSUE TITLE
Application accepted and rejected emails are not being sent to the applicant for status update. 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/WolfJobs-group66#17]

**Comment by shaziamuckram** [comment]
Emails are being sent from softwareengineering510@gmail.com to the applicant's email. @tahreemm @amaygada Does this work on your end? I have created a PR please review it.

**Comment by tahreemm** [comment]
I have verified by creating multiple users and accepting and rejecting them 
@amaygada please verify at your end

**Comment by amaygada** [comment]
done. closing issue
