### ISSUE TITLE
20 test cases per team member. 

### ISSUE THREAD

**Issue by shaziamuckram** [SAT510/WolfJobs-group66#18]
@amaygada @tahreemm Please add your share of test cases.

**Comment by shaziamuckram** [comment]
I have added 20 test cases in the fronted and fixed the failing ones. @tahreemm @amaygada any update on your end?

**Comment by amaygada** [comment]
I have added mine in the backend too.

**Comment by amaygada** [comment]
@tahreemm waiting for yoursss

**Comment by tahreemm** [comment]
@amaygada I am done as well - closing the issue
